name: VitalPlayerWeather
version: @version@
main: com.tamrielnetwork.vitalplayerweather.VitalPlayerWeather
api-version: 1.17
authors: [ Tamriel Network ]
website: https://tamriel.site
description: Gives players the ability to open a crafting interface.
commands:
  vitalplayerweather:
    description: "Main command"
    usage: "/vitalplayerweather"
permissions:
  vitalplayerweather.set:
    description: "Permission to change playerweather"
    default: op